# -*- coding: utf-8 -*-
"""Boxplot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_OVipJHZB-Zz2O2GPK4rKP-AcwOyBxKX
"""

#box plot ou diagrama de caixa
import matplotlib.pyplot as plt
import random #gera valores aleatorios

vetor = []

for i in range (100):
  numero_aleatorio = random.randint(0,50)
  vetor.append(numero_aleatorio)

plt.boxplot(vetor)
plt.title("meu box plot")
plt.show()